class Event < ApplicationRecord
  enum event_type: [
    :open_classroom,
    :workshops_cycle,
    :conference,
    :query,
    :course,
    :professional_course,
    :open_day,
    :e_learning,
    :explanation,
    :master,
    :workshop,
    :lecture,
    :postgraduate,
    :retreat,
    :open_week,
    :seminar,
    :sessions,
    :tests
  ], _prefix: :event_type

  enum event_category: [
    :Agriculture_and_Permaculture,
    :Company_and_Veterinary_Animals,
    :Architecture_Construction_and_Maintenance,
    :Archive_and_Documentation,
    :Arts_and_Design,
    :Astrology_Meditation_and_Spirituality,
    :Beauty_and_Personal_Styling,
    :Biology_and_Biochemistry,
    :DIY_and_Gardening,
    :House_and_decoration,
    :Political_sciences,
    :Coaching,
    :Communication,
    :Accounting_and_Taxation,
    :Cooking,
    :Dance_and_Theater,
    :Personal_and_Professional_Development,
    :Sport,
    :Economics_and_Law,
    :Education_and_Teaching,
    :Electricity_and_Electronics,
    :Writing,
    :Finance_and_Insurance,
    :Physics_and_chemistry,
    :Training_of_trainers,
    :Photography_and_Cinema,
    :Management_and_Administration,
    :History_and_Archeology,
    :Computing,
    :Journalism_and_Reportage,
    :Leisure_and_Family,
    :Languages_and_Literatures,
    :Marketing_and_Advertising,
    :Mathematics_and_Statistics,
    :Environment_and_Sustainability,
    :Financial_Markets,
    :Fashion_and_Sewing,
    :Music,
    :Psychology_and_Self_Esteem,
    :Health_Nutrition_and_Welfare,
    :Safty_and_hygiene_at_the_work,
    :Social_services,
    :Tourism_Hospitality_and_Catering
  ], _prefix: :event_category

end
